# Generated by Django 4.1.1 on 2022-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginlogout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
